
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS affiliate_level TEXT DEFAULT 'basic',
ADD COLUMN IF NOT EXISTS active_units_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS max_habits INTEGER DEFAULT 3,
ADD COLUMN IF NOT EXISTS max_tasks INTEGER DEFAULT 5,
ADD COLUMN IF NOT EXISTS max_fin_ops INTEGER DEFAULT 15,
ADD COLUMN IF NOT EXISTS cloud_sync_interval_days INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS has_ai_analytics BOOLEAN DEFAULT FALSE;
